name: 'Dev'
on: # rebuild any PRs and main branch changes
    pull_request:
    push:
        branches:
            - main
            - 'releases/*'

jobs:
    dev: # make sure the action works on a clean machine without building
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./
              with:
                  debug: false
                  build: npm run build
